version: '3'
services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./www:/var/www/html
    ports:
      - "8080:80"

  apache:
    image: httpd:2.4
    volumes:
      - ./www:/usr/local/apache2/htdocs
    ports:
      - "8082:80"

  mysql:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: Eventos
      MYSQL_USER: laravelArtisans
      MYSQL_PASSWORD: laravelArtisans
      MYSQL_ROOT_PASSWORD: laravelArtisans
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    links:
      - mysql:db
    ports:
      - "8081:80"
    environment:
      PMA_ARBITRARY: 1